### ISSUE TITLE
Active Position: Details corrections

### ISSUE THREAD

**Issue by OliverNChalk** [Monti/margin-trading-frontend#12]
Just a few changes to the details page for an active position:

![image](https://user-images.githubusercontent.com/11343499/43914959-98c33764-9c09-11e8-9a50-8e1657493341.png)

**Comment by boazberman** [comment]
![image](https://user-images.githubusercontent.com/14139261/44469888-19b99080-a631-11e8-98be-a7923fe64ee8.png)
This is the calculation for Position Holdings, is it ok? I dunno why, but it seems a bit off to me. (With the correct currency) @svechinsky

**Comment by OliverNChalk** [comment]
Should change it from 'Position Holdings' to 'Position Balance' and show the current STORM holdings of the contract. We could then move Assets Owed from position 7 to position 3.
