### ISSUE TITLE
Offers page doesn't filter orders with insufficient liquidity

### ISSUE THREAD

**Issue by OliverNChalk** [Monti/margin-trading-frontend#14]
While filtering on all other aspects, the offers screen will still show offers that do not have sufficient liquidity to fill the trader's position.

![image](https://user-images.githubusercontent.com/11343499/43998188-9ce5f4a8-9df8-11e8-8adf-c488d6cc22a1.png)

Resultant offer page:
![image](https://user-images.githubusercontent.com/11343499/43998192-a919b9a8-9df8-11e8-8eca-68e4a6001aee.png)

**Comment by svechinsky** [comment]
This is sorted if I'm correct?

**Comment by OliverNChalk** [comment]
Yes, thought it would have been nice to reference the commit that fixed it. We can start doing it moving forward to make documenting progress nice.
