### ISSUE TITLE
Prompts to sign transactions do not fade

### ISSUE THREAD

**Issue by OliverNChalk** [Monti/margin-trading-frontend#23]
**Describe the bug**
Prompts to sign transactions do not expire.

**To Reproduce**
1. Go to Loan Details page.
2. Click on alter accepted assets
3. Alter 1 or more assets.
4. Submitted and mining notifications will fade after time but prompts to sign on metamask will stay until page refresh.

**Expected behavior**
Prompts to sign messages on MetaMask should fade after a few seconds or after signing the message on MetaMask.

**Screenshots**
![image](https://user-images.githubusercontent.com/11343499/44474118-2a1e3b00-a632-11e8-9ef8-cf65d3e0ec4b.png)

**Browser Used:**
Chrome, cache purged

**Comment by svechinsky** [comment]
Was originally a feature not a bug but can change

**Comment by OliverNChalk** [comment]
What should it be doing? It stays with me forever, even after signing transactions and changing screens.
