### ISSUE TITLE
Questions regarding position balance

### ISSUE THREAD

**Issue by OliverNChalk** [Monti/margin-trading-frontend#30]
Just wondering how position balance is calculated, see the screenshot:
![image](https://user-images.githubusercontent.com/11343499/44605852-40232b80-a7eb-11e8-8d91-e030c018d50c.png)

Shouldn't position balance be the assets held by the smart contract, i.e. collateral staked + assets from sale?

Let me know if this is an error of it's trying to show something else.

**Comment by boazberman** [comment]
![image](https://user-images.githubusercontent.com/14139261/44617025-35f14380-a864-11e8-8552-12efcc8c36c6.png)
This is how position balance is calculated, and I said that it might be incorrect, in #12
The calculation explained: 
( Collateral Amount + Liquidation Amount ) * Collateral Token ETH rate

**Comment by OliverNChalk** [comment]
I think it makes the most sense to be denominated in what the contract is holding, especially if we have DAI written.

**Comment by boazberman** [comment]
Ok, committed.
