### ISSUE TITLE
Always failing transaction for closing a position

### ISSUE THREAD

**Issue by OliverNChalk** [Monti/margin-trading-frontend#31]
**Describe the bug**
When trying to close a position you own, the interface presents the following error:
![image](https://user-images.githubusercontent.com/11343499/44605941-82e50380-a7eb-11e8-8b7c-8b232c276a3c.png)

**To Reproduce**
1. Visit the details screen of one of your active positions
2. Select close position.
3. Observer error

**Browser Used:**
Chrome

**Additional information**
Tried with multiple positions of differing assets

**Comment by boazberman** [comment]
@svechinsky It seems like everything is ok in the client side, meaning it probably a problem in the contract, I've taken a look at the contract, and it will require vast research from me, to understand the contract, so tell me if you want me on that.

**Comment by svechinsky** [comment]
Closed here 461a4aeed194c38244c65ce8e03e65adbfaf2724
